//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtocolSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtocolSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;minecraft:air&quot;: {
        ///    &quot;id&quot;: 0,
        ///    &quot;explosion_resistance&quot;: 0.0,
        ///    &quot;item&quot;: 0,
        ///    &quot;default_state&quot;: 0,
        ///    &quot;class&quot;: &quot;AirBlock&quot;,
        ///    &quot;tint&quot;: &quot;minecraft:water_tint&quot;,
        ///    &quot;states&quot;: {
        ///      &quot;0&quot;: {
        ///        &quot;sound_type_volume&quot;: 1.0,
        ///        &quot;break_sound_type&quot;: 816,
        ///        &quot;step_sound_type&quot;: 824,
        ///        &quot;place_sound_type&quot;: 821,
        ///        &quot;hit_sound_type&quot;: 820,
        ///        &quot;fall_sound_type&quot;: 819,
        ///        &quot;is_opaque&quot;: false,
        ///        &quot;material&quot;: &quot;minecraft:air&quot;,
        ///        &quot;render&quot;: {
        ///          &quot;mode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string blocks {
            get {
                return ResourceManager.GetString("blocks", resourceCulture);
            }
        }
    }
}
