using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Redstone.Statistics
{
    public enum StatItems
    {
        LeaveGame = 0,
        PlayOneMinute = 1,
        TimeSinceDeath = 2,
        TimeSinceRest = 3,
        SneakTime = 4,
        WalkOneCm = 5,
        CrouchOneCm = 6,
        SprintOneCm = 7,
        WalkOnWaterOneCm = 8,
        FallOneCm = 9,
        ClimbOneCm = 10,
        FlyOneCM = 11,
        WalkUnderWaterOneCm = 12,
        MinecartOneCm = 13,
        BoatOneCm = 14,
        PigOneCm = 15,
        HorseOneCm = 16,
        AviateOneCm = 17,
        SwimOneCm = 18,
        StriderOneCm = 19,
        Jump = 20,
        Drop = 21,
        DamageDealt = 22,
        DamageDealtAbsorbed = 23,
        DamageDealtResisted = 24,
        DamageTaken = 25,
        DamageBlockedByShield = 26,
        DamageAbsorbed = 27,
        DamageResisted = 28,
        Deaths = 29,
        MobKills = 30,
        AnimalsBred = 31,
        PlayerKills = 32,
        FishCaught = 33,
        TalkedToVillager = 34,
        TradedWithVillager = 35,
        EatCakeSlice = 36,
        FillCauldron = 37,
        UseCauldron = 38,
        CleanArmor = 39,
        CleanBanner = 40,
        CleanShulkerBox = 41,
        InteractWithBrewingStand = 42,
        InteractWithBeacon = 43,
        InspectDropper = 44,
        InspectHopper = 45,
        InspectDispenser = 46,
        PlayNoteblock = 47,
        TuneNoteblock = 48,
        PotFlower = 49,
        TriggerTrappedChest = 50,
        OpenEnderChest = 51,
        EnchantItem = 52,
        PlayRecord = 53,
        InteractWithFurnace = 54,
        InteractWithCraftingTable = 55,
        OpenChest = 56,
        SleepInBed = 57,
        OpenShulkerBox = 58,
        OpenBarrel = 59,
        InteractWithBlastFurnace = 60,
        InteractWithSmoker = 61,
        InteractWithLectern = 62,
        InteractWithCampfire = 63,
        InteractWithCartographyTable = 64,
        InteractWithLoom = 65,
        InteractWithStonecutter = 66,
        BellRing = 67,
        RaidTrigger = 68,
        RaidWin = 69,
        InteractWithAnvil = 70,
        InteractWithGrindstone = 71,
        TargetHit = 72,
        InteractWithSmithingTable = 73
    }
}
