using Redstone.Core.Types;
using System;
using System.Collections.Generic;
using System.Text;

namespace Redstone.Core
{
    public sealed class Registry
    {
        public static readonly Dictionary<VarInt, Identifier> Particles = new()
        {
            { 0, "angry_villager" },
            { 1, "block" },
            { 2, "block_marker" },
            { 3, "bubble" },
            { 4, "cloud" },
            { 5, "copper_fire_flame" },
            { 6, "crit" },
            { 7, "damage_indicator" },
            { 8, "dragon_breath" },
            { 9, "dripping_lava" },
            { 10, "falling_lava" },
            { 11, "landing_lava" },
            { 12, "dripping_water" },
            { 13, "falling_water" },
            { 14, "dust" },
            { 15, "dust_color_transition" },
            { 16, "effect" },
            { 17, "elder_guardian" },
            { 18, "enchanted_hit" },
            { 19, "enchant" },
            { 20, "end_rod" },
            { 21, "entity_effect" },
            { 22, "exposion_emitter" },
            { 23, "explosion" },
            { 24, "gust" },
            { 25, "small_gust" },
            { 26, "gust_emitter_large" },
            { 27, "gust_emitter_small" },
            { 28, "sonic_boom" },
            { 29, "falling_dust" },
            { 30, "firework" },
            { 31, "fishing" },
            { 32, "flame" },
            { 33, "infested" },
            { 34, "cherry_leaves" },
            { 35, "pale_oak_leaves" },
            { 36, "tinted_leaves" },
            { 37, "sculk_soul" },
            { 38, "sculk_charge" },
            { 39, "sculk_charge_pop" },
            { 40, "soul_fire_flame" },
            { 41, "soul" },
            { 42, "flash" },
            { 43, "happy_villager" },
            { 44, "composter" },
            { 45, "heart" },
            { 46, "instant_effect" },
            { 47, "item" },
            { 48, "vibration" },
            { 49, "trail" },
            { 50, "item_slime" },
            { 51, "item_cobweb" },
            { 52, "item_snowball" },
            { 53, "large_smoke" },
            { 54, "lava" },
            { 55, "mycelim" },
            { 56, "note" },
            { 57, "poof" },
            { 58, "portal" },
            { 59, "rain" },
            { 60, "smoke" },
            { 61, "white_smoke" },
            { 62, "sneeze" },
            { 63, "spit" },
            { 64, "squid_ink" },
            { 65, "sweep_attack" },
            { 66, "totem_of_undying" },
            { 67, "underwater" },
            { 68, "splash" },
            { 69, "witch" },
            { 70, "bubble_pop" },
            { 71, "current_down" },
            { 72, "bubble_column_up" },
            { 73, "nautilus" },
            { 74, "dolphin" },
            { 75, "campfire_cosy_smoke" },
            { 76, "campfire_signal_smoke" },
            { 77, "dripping_honey" },
            { 78, "falling_honey" },
            { 79, "landing_honey" },
            { 80, "falling_nectar" },
            { 81, "fallling_spore_blossom" },
            { 82, "ash" },
            { 83, "crimson_spore" },
            { 84, "warped_spore" },
            { 85, "spore_blossom_air" },
            { 86, "dripping_obsidian_tear" },
            { 87, "falling_obsidian_tear"  },
            { 88, "landing_obsidian_tear" },
            { 89, "reverse_portal" },
            { 90, "white_ash" },
            { 91, "small_flame" },
            { 92, "snowflake" },
            { 93, "dripping_dripstone_lava" },
            { 94, "falling_dripstone_lava" },
            { 95, "dripping_dripstone_water" },
            { 96, "falling_dripstone_water" },
            { 97, "glow_squid_ink"  },
            {  98, "glow"  },
            { 99, "wax_on" },
            { 100, "wax_off" },
            { 101, "electric_spark" },
            { 102, "scrape"  },
            { 103, "shriek" },
            { 104, "egg_crack" },
            { 105, "dust_plume" },
            { 106, "trial_spawner_detection" },
            { 107, "trial_spawner_detection_ominous" },
            { 108, "vault_connection" },
            { 109, "dust_pillar" },
            { 110, "ominous_spawning" },
            { 111, "raid_omen" },
            { 112, "trial_omen" },
            { 113, "block_crumble" },
            { 114, "firefly" }
        };
    }
}
